import { ZelapiService, ZelapiCountry, ZelapiOtpItem, ZelapiDetailedStats, ZelapiNumber } from './types';

export const MOCK_SERVICES: ZelapiService[] = [
  { name: 'WhatsApp', code: 'wa', available: 428, category: 'Messaging' },
  { name: 'Telegram', code: 'tg', available: 312, category: 'Messaging' },
  { name: 'Google / Gmail', code: 'go', available: 589, category: 'Tech & Cloud' },
  { name: 'TikTok', code: 'tk', available: 215, category: 'Social Media' },
  { name: 'OpenAI / ChatGPT', code: 'oa', available: 184, category: 'AI & Tools' },
  { name: 'Instagram / Facebook', code: 'fb', available: 340, category: 'Social Media' },
  { name: 'Discord', code: 'ds', available: 167, category: 'Gaming & Social' },
  { name: 'X / Twitter', code: 'tw', available: 142, category: 'Social Media' },
  { name: 'Shopee', code: 'sh', available: 290, category: 'E-Commerce' },
  { name: 'Tokopedia / Gojek', code: 'gk', available: 210, category: 'E-Commerce' },
  { name: 'Dana', code: 'dn', available: 175, category: 'Fintech' },
  { name: 'OVO', code: 'ov', available: 130, category: 'Fintech' },
  { name: 'PayPal', code: 'pp', available: 95, category: 'Fintech' },
  { name: 'Microsoft', code: 'ms', available: 310, category: 'Tech & Cloud' },
  { name: 'Steam', code: 'st', available: 88, category: 'Gaming' },
  { name: 'Netflix', code: 'nf', available: 64, category: 'Streaming' },
  { name: 'Any Other (Lainnya)', code: 'ot', available: 1250, category: 'General' },
];

export const MOCK_COUNTRIES: Record<string, ZelapiCountry[]> = {
  default: [
    { name: 'Indonesia', code: 'ID', prefix: '+62', available: 540 },
    { name: 'United States', code: 'US', prefix: '+1', available: 320 },
    { name: 'United Kingdom', code: 'GB', prefix: '+44', available: 210 },
    { name: 'Malaysia', code: 'MY', prefix: '+60', available: 180 },
    { name: 'Philippines', code: 'PH', prefix: '+63', available: 145 },
    { name: 'India', code: 'IN', prefix: '+91', available: 410 },
    { name: 'Vietnam', code: 'VN', prefix: '+84', available: 95 },
    { name: 'Thailand', code: 'TH', prefix: '+66', available: 110 },
    { name: 'Brazil', code: 'BR', prefix: '+55', available: 165 },
    { name: 'Germany', code: 'DE', prefix: '+49', available: 90 },
  ],
};

export const MOCK_LIVE_OTPS: ZelapiOtpItem[] = [
  {
    id: 'otp-101',
    number: '+628826920****',
    service: 'WhatsApp',
    otp: '849201',
    message: 'Your WhatsApp Business code: 849-201. Do not share this code.',
    received_at: new Date(Date.now() - 15000).toISOString(),
    sender: 'WhatsApp',
    country: 'Indonesia',
  },
  {
    id: 'otp-102',
    number: '+1415982****',
    service: 'Telegram',
    otp: '49281',
    message: 'Telegram code: 49281. You can also tap on this link to log in.',
    received_at: new Date(Date.now() - 42000).toISOString(),
    sender: 'Telegram',
    country: 'United States',
  },
  {
    id: 'otp-103',
    number: '+628139411****',
    service: 'Google / Gmail',
    otp: '730192',
    message: 'G-730192 is your Google verification code.',
    received_at: new Date(Date.now() - 78000).toISOString(),
    sender: 'Google',
    country: 'Indonesia',
  },
  {
    id: 'otp-104',
    number: '+6012849****',
    service: 'Shopee',
    otp: '551940',
    message: '551940 adalah kode verifikasi Shopee Anda. RAHASIA, jangan berikan ke siapapun.',
    received_at: new Date(Date.now() - 110000).toISOString(),
    sender: 'Shopee',
    country: 'Malaysia',
  },
  {
    id: 'otp-105',
    number: '+628571092****',
    service: 'TikTok',
    otp: '204918',
    message: '[TikTok] 204918 is your verification code.',
    received_at: new Date(Date.now() - 155000).toISOString(),
    sender: 'TikTok',
    country: 'Indonesia',
  },
  {
    id: 'otp-106',
    number: '+44791112****',
    service: 'OpenAI / ChatGPT',
    otp: '381902',
    message: 'Your OpenAI verification code is 381902.',
    received_at: new Date(Date.now() - 210000).toISOString(),
    sender: 'OpenAI',
    country: 'United Kingdom',
  },
  {
    id: 'otp-107',
    number: '+628965543****',
    service: 'Dana',
    otp: '9182',
    message: 'JANGAN BERIKAN KODE INI KE SIAPAPUN. PIN/OTP DANA Anda: 9182',
    received_at: new Date(Date.now() - 280000).toISOString(),
    sender: 'DANA',
    country: 'Indonesia',
  }
];

export const MOCK_STATS_DETAILED: ZelapiDetailedStats = {
  period: 'daily',
  total_requests: 14850,
  successful_otps: 13920,
  success_rate: 93.7,
  active_virtual_numbers: 148,
  avg_delivery_time_seconds: 4.8,
  server_status: 'online',
  uptime_percentage: 99.94,
  top_services: [
    { name: 'WhatsApp', requests: 4890, success_rate: 96.2 },
    { name: 'Telegram', requests: 3420, success_rate: 95.1 },
    { name: 'Google', requests: 2150, success_rate: 94.0 },
    { name: 'TikTok', requests: 1680, success_rate: 91.5 },
    { name: 'Shopee / E-Com', requests: 1420, success_rate: 92.8 },
    { name: 'OpenAI', requests: 1290, success_rate: 89.4 },
  ],
  hourly_distribution: [
    { hour: '00:00', count: 320 },
    { hour: '03:00', count: 180 },
    { hour: '06:00', count: 420 },
    { hour: '09:00', count: 980 },
    { hour: '12:00', count: 1450 },
    { hour: '15:00', count: 1820 },
    { hour: '18:00', count: 1640 },
    { hour: '21:00', count: 1230 },
  ],
};
